version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: ${PGDATA}
    networks:
      defaultnet:
        aliases:
          - ${POSTGRES_HOSTNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db:${PGDATA}
      - ./scripts:/docker-entrypoint-initdb.d
  app:
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
        - defaultnet
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - RAINDROP_TOKEN=${RAINDROP_TOKEN}
      - TODOIST_TOKEN=${TODOIST_TOKEN}
networks:
  defaultnet: